services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-platform-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: food-platform-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_platform
      MYSQL_USER: food_user
      MYSQL_PASSWORD: food_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
